### PR TITLE
Cleaned up some documentation

### PR DESCRIPTION
**Pull request by devandanger**
Ideally json files [shouldn't have comments in them](https://stackoverflow.com/questions/244777/can-comments-be-used-in-json).  This made it difficult to peruse via github so I removed them from the JSON and added them into a separate markdown file and documented them with the existing information.

It was also difficult to find originally so I linked to them directly using the github's [relative link feature](https://stackoverflow.com/questions/7653483/github-relative-link-in-markdown-file).

### CODE REVIEW

**Comment by devandanger** [comment]
@sferg-msft any interest in this documentation updates?

**Comment by sferg-msft** [comment]
So I get that json doesn't technically support comments, could you expand upon what you meant by it made it difficult to persuse via github?

**Comment by sferg-msft** [comment]
Nevermind, I just noticed github puts a lot of red there.  Thanks for doing this!

**Comment by devandanger** [comment]
np!

**Pull request merged**
